INSERT INTO public.utenti (
    "[studenti]_username", e_premium, password)
VALUES 
    ('jdoe1', true, 'password1'),
    ('asmith1', false, 'password2'),
    ('bwhite1', true, 'password3'),
    ('clark1', false, 'password4'),
    ('ddavis1', true, 'password5'),
    ('emiller1', false, 'password6'),
    ('fthomas1', true, 'password7'),
    ('gjones1', false, 'password8'),
    ('hlee1', true, 'password9'),
    ('ikim1', false, 'password10'),
    ('jdoe2', true, 'password11'),
    ('asmith2', false, 'password12'),
    ('bwhite2', true, 'password13'),
    ('clark2', false, 'password14'),
    ('ddavis2', true, 'password15'),
    ('emiller2', false, 'password16'),
    ('fthomas2', true, 'password17'),
    ('gjones2', false, 'password18'),
    ('hlee2', true, 'password19'),
    ('ikim2', false, 'password20'),
    ('jdoe3', true, 'password21'),
    ('asmith3', false, 'password22'),
    ('bwhite3', true, 'password23'),
    ('clark3', false, 'password24'),
    ('ddavis3', true, 'password25');
