
ALTER TABLE Utenti ADD COLUMN nome VARCHAR(50);
ALTER TABLE Utenti ADD COLUMN cognome VARCHAR(50);
ALTER TABLE Utenti ADD COLUMN anno_nascita INT;
ALTER TABLE Utenti ADD COLUMN luogo_nascita VARCHAR(100);
ALTER TABLE Utenti ADD COLUMN foto BYTEA;
ALTER TABLE Utenti ADD COLUMN recapito_telefonico VARCHAR(15);
ALTER TABLE Utenti ADD COLUMN numero_matricola VARCHAR(20);
ALTER TABLE Utenti ADD COLUMN corso_di_studi VARCHAR(100);
